const config = {
	LOGS : [],//'verbose','facilityprogram','reference','rules','boardcertify','grouppractice','hospitalaffiliation','language','specialty','providertier','addresses','verbose','global','network'
	REFTRANSLATIONS : [{column : 'Hospital Affiliation', replace : 'N', value : 'N/A'},
		{column : 'Hospital Affiliation', replace : 'N', value : 'Unknown'},
		{column : 'Hospital Affiliation', replace : 'Y', value : '[\d ]+'},
		{column : 'Network', replace : '01', value : 'Florida Hospital Individual plans'},
		{column : 'Network', replace : '01', value : 'Health First Group Plans'},
		{column : 'Network', replace : '01', value : 'Health First Individual Plans'},
		{column : 'Network', replace : '01', value : 'Health First Associate Plans'},
		{column : 'Network', replace : '01', value : 'Brevard County Employee Health Care Plans'},
		{column : 'Network', replace : '02', value : 'Health First Medicare Advantage Plans'},
		{column : 'Language', replace : '001', value : 'Abkhazian'},
		{column : 'Language', replace : '078', value : 'Macedonian'},
		{column : 'Language', replace : '002', value : 'Afan (Oromo)'},
		{column : 'Language', replace : '079', value : 'Malagasy'},
		{column : 'Language', replace : '003', value : 'Afar'},
		{column : 'Language', replace : '080', value : 'Malay'},
		{column : 'Language', replace : '004', value : 'Afrikaans'},
		{column : 'Language', replace : '081', value : 'Malaya'},
		{column : 'Language', replace : '005', value : 'Albanian'},
		{column : 'Language', replace : '082', value : 'Malayalam'},
		{column : 'Language', replace : '006', value : 'American Sign Language'},
		{column : 'Language', replace : '083', value : 'Maltese'},
		{column : 'Language', replace : '007', value : 'Amharic'},
		{column : 'Language', replace : '084', value : 'Mandarin'},
		{column : 'Language', replace : '008', value : 'Arabic'},
		{column : 'Language', replace : '085', value : 'Maori'},
		{column : 'Language', replace : '009', value : 'Armenian'},
		{column : 'Language', replace : '086', value : 'Marathi'},
		{column : 'Language', replace : '010', value : 'Assamese'},
		{column : 'Language', replace : '087', value : 'Moldavian'},
		{column : 'Language', replace : '011', value : 'Bashkir'},
		{column : 'Language', replace : '088', value : 'Mongolian'},
		{column : 'Language', replace : '012', value : 'Basque'},
		{column : 'Language', replace : '089', value : 'Nauru'},
		{column : 'Language', replace : '013', value : 'Bengali'},
		{column : 'Language', replace : '090', value : 'Nepali'},
		{column : 'Language', replace : '014', value : 'Bengali;Bangla'},
		{column : 'Language', replace : '091', value : 'Norwegian'},
		{column : 'Language', replace : '015', value : 'Bhutani'},
		{column : 'Language', replace : '092', value : 'Occitan'},
		{column : 'Language', replace : '016', value : 'Bicolano'},
		{column : 'Language', replace : '093', value : 'Oriya'},
		{column : 'Language', replace : '017', value : 'Bihari'},
		{column : 'Language', replace : '094', value : 'Pashto;Pushto'},
		{column : 'Language', replace : '018', value : 'Bislama'},
		{column : 'Language', replace : '095', value : 'Persian'},
		{column : 'Language', replace : '019', value : 'Breton'},
		{column : 'Language', replace : '096', value : 'Persian (Farsi)'},
		{column : 'Language', replace : '020', value : 'Bulgarian'},
		{column : 'Language', replace : '097', value : 'Polish'},
		{column : 'Language', replace : '021', value : 'Burmese'},
		{column : 'Language', replace : '098', value : 'Portugese'},
		{column : 'Language', replace : '022', value : 'Byelorussian'},
		{column : 'Language', replace : '099', value : 'Portuguese'},
		{column : 'Language', replace : '023', value : 'Cambodian'},
		{column : 'Language', replace : '100', value : 'Punjabi'},
		{column : 'Language', replace : '024', value : 'Cantonese'},
		{column : 'Language', replace : '101', value : 'Quechua'},
		{column : 'Language', replace : '025', value : 'Catalan'},
		{column : 'Language', replace : '102', value : 'Rhaeto-Romance'},
		{column : 'Language', replace : '026', value : 'Chinese'},
		{column : 'Language', replace : '103', value : 'Romanian'},
		{column : 'Language', replace : '027', value : 'Corsican'},
		{column : 'Language', replace : '104', value : 'Russian'},
		{column : 'Language', replace : '028', value : 'Croatian'},
		{column : 'Language', replace : '105', value : 'Samoan'},
		{column : 'Language', replace : '029', value : 'Czech'},
		{column : 'Language', replace : '106', value : 'Sangho'},
		{column : 'Language', replace : '030', value : 'Danish'},
		{column : 'Language', replace : '107', value : 'Sanskrit'},
		{column : 'Language', replace : '031', value : 'Dutch'},
		{column : 'Language', replace : '108', value : 'Scot Gaelic'},
		{column : 'Language', replace : '032', value : 'English'},
		{column : 'Language', replace : '109', value : 'Serbian'},
		{column : 'Language', replace : '033', value : 'Esperanto'},
		{column : 'Language', replace : '110', value : 'Serbo-Croatian'},
		{column : 'Language', replace : '034', value : 'Estonian'},
		{column : 'Language', replace : '111', value : 'Sesotho'},
		{column : 'Language', replace : '035', value : 'Faroese'},
		{column : 'Language', replace : '112', value : 'Setswana'},
		{column : 'Language', replace : '036', value : 'Farsi'},
		{column : 'Language', replace : '113', value : 'Shona'},
		{column : 'Language', replace : '037', value : 'Fiji'},
		{column : 'Language', replace : '114', value : 'Sign Language'},
		{column : 'Language', replace : '038', value : 'Filipino'},
		{column : 'Language', replace : '115', value : 'Sindhi'},
		{column : 'Language', replace : '039', value : 'Finnish'},
		{column : 'Language', replace : '116', value : 'Singhalese'},
		{column : 'Language', replace : '040', value : 'French'},
		{column : 'Language', replace : '117', value : 'Siswati'},
		{column : 'Language', replace : '041', value : 'Frisian'},
		{column : 'Language', replace : '118', value : 'Slovak'},
		{column : 'Language', replace : '042', value : 'Galican'},
		{column : 'Language', replace : '119', value : 'Slovenian'},
		{column : 'Language', replace : '043', value : 'Georgian'},
		{column : 'Language', replace : '120', value : 'Somali'},
		{column : 'Language', replace : '044', value : 'German'},
		{column : 'Language', replace : '121', value : 'Spanish'},
		{column : 'Language', replace : '045', value : 'Greek'},
		{column : 'Language', replace : '122', value : 'Spanish (Medical)'},
		{column : 'Language', replace : '046', value : 'Greenlandic'},
		{column : 'Language', replace : '123', value : 'Sundanese'},
		{column : 'Language', replace : '047', value : 'Guarani'},
		{column : 'Language', replace : '124', value : 'Swahili'},
		{column : 'Language', replace : '048', value : 'Gujarati'},
		{column : 'Language', replace : '125', value : 'Swedish'},
		{column : 'Language', replace : '049', value : 'Gurri'},
		{column : 'Language', replace : '126', value : 'Tagalog'},
		{column : 'Language', replace : '050', value : 'Hausa'},
		{column : 'Language', replace : '127', value : 'Taiwanese'},
		{column : 'Language', replace : '051', value : 'Hebrew'},
		{column : 'Language', replace : '128', value : 'Tajik'},
		{column : 'Language', replace : '052', value : 'Hindi'},
		{column : 'Language', replace : '129', value : 'Tamil'},
		{column : 'Language', replace : '053', value : 'Hungarian'},
		{column : 'Language', replace : '130', value : 'Tatar'},
		{column : 'Language', replace : '054', value : 'Icelandic'},
		{column : 'Language', replace : '131', value : 'Telugu'},
		{column : 'Language', replace : '055', value : 'Indian'},
		{column : 'Language', replace : '132', value : 'Thai'},
		{column : 'Language', replace : '056', value : 'Indonesian'},
		{column : 'Language', replace : '133', value : 'Tibetan'},
		{column : 'Language', replace : '057', value : 'Interlingua'},
		{column : 'Language', replace : '134', value : 'Tigrinya'},
		{column : 'Language', replace : '058', value : 'Interlingue'},
		{column : 'Language', replace : '135', value : 'Tonga'},
		{column : 'Language', replace : '059', value : 'Inuktitut'},
		{column : 'Language', replace : '136', value : 'Tsonga'},
		{column : 'Language', replace : '060', value : 'Inupiak'},
		{column : 'Language', replace : '137', value : 'Turkish'},
		{column : 'Language', replace : '061', value : 'Irish'},
		{column : 'Language', replace : '138', value : 'Turkmen'},
		{column : 'Language', replace : '062', value : 'Italian'},
		{column : 'Language', replace : '139', value : 'Twi'},
		{column : 'Language', replace : '063', value : 'Japanese'},
		{column : 'Language', replace : '140', value : 'Uigur'},
		{column : 'Language', replace : '064', value : 'Javanese'},
		{column : 'Language', replace : '141', value : 'Ukrainian'},
		{column : 'Language', replace : '065', value : 'Kannada'},
		{column : 'Language', replace : '142', value : 'Urdel'},
		{column : 'Language', replace : '066', value : 'Kashmiri'},
		{column : 'Language', replace : '143', value : 'Urdu'},
		{column : 'Language', replace : '067', value : 'Kazakh'},
		{column : 'Language', replace : '144', value : 'Uzbek'},
		{column : 'Language', replace : '068', value : 'Kinyarwanda'},
		{column : 'Language', replace : '145', value : 'Vietnamese'},
		{column : 'Language', replace : '069', value : 'Kirghiz'},
		{column : 'Language', replace : '146', value : 'Volapuk'},
		{column : 'Language', replace : '070', value : 'Korean'},
		{column : 'Language', replace : '147', value : 'Welsh'},
		{column : 'Language', replace : '071', value : 'Kurdish'},
		{column : 'Language', replace : '148', value : 'Wolof'},
		{column : 'Language', replace : '072', value : 'Kurundi'},
		{column : 'Language', replace : '149', value : 'Xhosa'},
		{column : 'Language', replace : '073', value : 'Laothian'},
		{column : 'Language', replace : '150', value : 'Yiddish'},
		{column : 'Language', replace : '074', value : 'Latin'},
		{column : 'Language', replace : '151', value : 'Yoruba'},
		{column : 'Language', replace : '075', value : 'Latvian;Lettish'},
		{column : 'Language', replace : '152', value : 'Zerbaijani'},
		{column : 'Language', replace : '076', value : 'Lingala'},
		{column : 'Language', replace : '153', value : 'Zhuang'},
		{column : 'Language', replace : '077', value : 'Lithuanian'},
		{column : 'Language', replace : '154', value : 'Zulu'},
		{column : 'Language', replace : '159', value : 'Haitian Creole'},
		{column : 'Language', replace : '155', value : 'Bini'},
		{column : 'Language', replace : '160', value : 'Igbo'},
		{column : 'Language', replace : '156', value : 'Cebuano'},
		{column : 'Language', replace : '161', value : 'Pangasinam'},
		{column : 'Language', replace : '157', value : 'Chin'},
		{column : 'Language', replace : '162', value : 'Creole'},
		{column : 'Language', replace : '158', value : 'Enets'},
		{column : 'Specialty', replace : 'A01', value :	'Adolescent Medicine'},
		{column : 'Specialty', replace : 'A02', value :	'Adult Nurse Practitioner'},
		{column : 'Specialty', replace : 'A03', value :	'Advanced Heart Failure & Transplant Cardiology'},
		{column : 'Specialty', replace : 'A04', value :	'Allergy & Immunology'},
		{column : 'Specialty', replace : 'A05', value :	'Anesthesiology'},
		{column : 'Specialty', replace : 'A06', value :	'Audiology'},
		{column : 'Specialty', replace : 'B01', value :	'Bariatric Surgery'},
		{column : 'Specialty', replace : 'B02', value :	'Behavioral Health'},
		{column : 'Specialty', replace : 'B03', value :	'Breast Surgery'},
		{column : 'Specialty', replace : 'C01', value :	'Cardiology'},
		{column : 'Specialty', replace : 'C02', value :	'Cardiology, Interventional'},
		{column : 'Specialty', replace : 'C03', value :	'Cardiothoracic Surgery'},
		{column : 'Specialty', replace : 'C04', value :	'Cardiovascular Surgery'},
		{column : 'Specialty', replace : 'C05', value :	'Certified Diabetes Educator'},
		{column : 'Specialty', replace : 'C06', value :	'Certified Nurse Midwife'},
		{column : 'Specialty', replace : 'C07', value :	'Child and Adolescent Psychiatry'},
		{column : 'Specialty', replace : 'C08', value :	'Chiropractic'},
		{column : 'Specialty', replace : 'C09', value :	'Genetics'},
		{column : 'Specialty', replace : 'C10', value :	'Clinical Neurophysiology'},
		{column : 'Specialty', replace : 'C11', value :	'Clinical Neuropsychology'},
		{column : 'Specialty', replace : 'C12', value :	'Clinical Psychology'},
		{column : 'Specialty', replace : 'C13', value :	'Colon & Rectal Surgery'},
		{column : 'Specialty', replace : 'C14', value :	'Critical Care Medicine'},
		{column : 'Specialty', replace : 'C15', value :	'Concierge PCP '},
		{column : 'Specialty', replace : 'D01', value :	'Dermatology'},
		{column : 'Specialty', replace : 'D02', value :	'Dermatopathology'},
		{column : 'Specialty', replace : 'D03', value :	'Developmental Behavioral Pediatrics'},
		{column : 'Specialty', replace : 'E01', value :	'Electrophysiology, Clinical Cardiac'},
		{column : 'Specialty', replace : 'E02', value :	'Endocrinology'},
		{column : 'Specialty', replace : 'F01', value :	'Family Medicine'},
		{column : 'Specialty', replace : 'F02', value :	'Female Pelvic Medicine and Reconstructive Surgery'},
		{column : 'Specialty', replace : 'F03', value :	'Foot & Ankle Surgery'},
		{column : 'Specialty', replace : 'F04', value :	'Forensic Psychiatry'},
		{column : 'Specialty', replace : 'G01', value :	'Gastroenterology'},
		{column : 'Specialty', replace : 'G02', value :	'General Practice'},
		{column : 'Specialty', replace : 'G03', value :	'General Surgery'},
		{column : 'Specialty', replace : 'G04', value :	'Geriatric Medicine'},
		{column : 'Specialty', replace : 'G05', value :	'Geriatric Psychiatry'},
		{column : 'Specialty', replace : 'G06', value :	'Gynecologic Oncology'},
		{column : 'Specialty', replace : 'G07', value :	'Gynecology'},
		{column : 'Specialty', replace : 'H01', value :	'Hematology'},
		{column : 'Specialty', replace : 'H02', value :	'Hematology & Oncology'},
		{column : 'Specialty', replace : 'H03', value :	'Hepatology'},
		{column : 'Specialty', replace : 'H04', value :	'Hospice and Palliative Care'},
		{column : 'Specialty', replace : 'I01', value :	'Infectious Disease'},
		{column : 'Specialty', replace : 'I02', value :	'Internal Medicine'},
		{column : 'Specialty', replace : 'L01', value :	'Licensed Clinical Social Worker (LCSW)'},
		{column : 'Specialty', replace : 'L02', value :	'Licensed Mental Health Counselor (LMHC)'},
		{column : 'Specialty', replace : 'M01', value :	'Licensed Marriage and Family Therapy'},
		{column : 'Specialty', replace : 'M02', value :	'Maternal & Fetal Medicine'},
		{column : 'Specialty', replace : 'N01', value :	'Nephrology'},
		{column : 'Specialty', replace : 'N02', value :	'Neurosurgery'},
		{column : 'Specialty', replace : 'N03', value :	'Neurology'},
		{column : 'Specialty', replace : 'N04', value :	'Neuromuscular Medicine'},
		{column : 'Specialty', replace : 'N05', value :	'Neuropsychology'},
		{column : 'Specialty', replace : 'N06', value :	'Neuroradiology'},
		{column : 'Specialty', replace : 'O01', value :	'Obstetrics'},
		{column : 'Specialty', replace : 'O02', value :	'Obstetrics & Gynecology'},
		{column : 'Specialty', replace : 'O03', value :	'Oncology'},
		{column : 'Specialty', replace : 'O04', value :	'Ophthalmology'},
		{column : 'Specialty', replace : 'O05', value :	'Optometry'},
		{column : 'Specialty', replace : 'O06', value :	'Oral & Maxillofacial Surgery'},
		{column : 'Specialty', replace : 'O07', value :	'Orthopaedic Surgery'},
		{column : 'Specialty', replace : 'O08', value :	'Orthopaedic Surgery of the Spine'},
		{column : 'Specialty', replace : 'O09', value :	'Otolaryngology - ENT'},
		{column : 'Specialty', replace : 'O10', value :	'Orthopaedic Sports Medicine'},
		{column : 'Specialty', replace : 'O11', value :	'Occupational Medicine'},
		{column : 'Specialty', replace : 'O12', value :	'Ophthalmic Plastic and Reconstructive Surgery'},
		{column : 'Specialty', replace : 'P01', value :	'Pain Management'},
		{column : 'Specialty', replace : 'P02', value :	'Pediatric Allergy & Immunology'},
		{column : 'Specialty', replace : 'P03', value :	'Pediatric Cardiology'},
		{column : 'Specialty', replace : 'P04', value :	'Pediatric Cardiothoracic Surgery'},
		{column : 'Specialty', replace : 'P05', value :	'Pediatric Critical Care Medicine'},
		{column : 'Specialty', replace : 'P06', value :	'Pediatric Dermatology'},
		{column : 'Specialty', replace : 'P07', value :	'Pediatric Endocrinology'},
		{column : 'Specialty', replace : 'P08', value :	'Pediatric Gastroenterology'},
		{column : 'Specialty', replace : 'P09', value :	'Pediatric General Surgery'},
		{column : 'Specialty', replace : 'P10', value :	'Pediatric Hematology - Oncology'},
		{column : 'Specialty', replace : 'P11', value :	'Pediatric Infectious Diseases'},
		{column : 'Specialty', replace : 'P12', value :	'Pediatric Nephrology'},
		{column : 'Specialty', replace : 'P13', value :	'Pediatric Neurology'},
		{column : 'Specialty', replace : 'P14', value :	'Pediatric Neurosurgery'},
		{column : 'Specialty', replace : 'P15', value :	'Pediatric Ophthalmology'},
		{column : 'Specialty', replace : 'P16', value :	'Pediatric Orthopaedics'},
		{column : 'Specialty', replace : 'P17', value :	'Pediatric Otolaryngology - ENT'},
		{column : 'Specialty', replace : 'P18', value :	'Pediatric Pathology'},
		{column : 'Specialty', replace : 'P19', value :	'Pediatric Pulmonology'},
		{column : 'Specialty', replace : 'P20', value :	'Pediatric Rheumatology'},
		{column : 'Specialty', replace : 'P21', value :	'Pediatric Urology'},
		{column : 'Specialty', replace : 'P22', value :	'Pediatrics'},
		{column : 'Specialty', replace : 'P23', value :	'Physical Medicine & Rehabilitation'},
		{column : 'Specialty', replace : 'P24', value :	'Plastic & Reconstructive Surgery'},
		{column : 'Specialty', replace : 'P25', value :	'Podiatry'},
		{column : 'Specialty', replace : 'P26', value :	'Psychiatry'},
		{column : 'Specialty', replace : 'P27', value :	'Psychiatry, Brain Injury'},
		{column : 'Specialty', replace : 'P28', value :	'Psychology'},
		{column : 'Specialty', replace : 'P29', value :	'Psychosomatic Medicine'},
		{column : 'Specialty', replace : 'P30', value :	'Pulmonology'},
		{column : 'Specialty', replace : 'P32', value :	'Preventive Medicine'},
		{column : 'Specialty', replace : 'R01', value :	'Radiation Oncology'},
		{column : 'Specialty', replace : 'R02', value :	'Reproductive Endocrinology - Infertility'},
		{column : 'Specialty', replace : 'R03', value :	'Rheumatology'},
		{column : 'Specialty', replace : 'R04', value :	'Radiology-Diagnostic'},
		{column : 'Specialty', replace : 'S01', value :	'Sleep Medicine'},
		{column : 'Specialty', replace : 'S02', value :	'Social Work'},
		{column : 'Specialty', replace : 'S03', value :	'Sports Medicine'},
		{column : 'Specialty', replace : 'S04', value :	'Surgical Critical Care'},
		{column : 'Specialty', replace : 'S05', value :	'Surgical Oncology'},
		{column : 'Specialty', replace : 'S06', value :	'Speech Language Pathology'},
		{column : 'Specialty', replace : 'U01', value :	'Undersea and Hyperbaric Medicine'},
		{column : 'Specialty', replace : 'U02', value :	'Urogynecology'},
		{column : 'Specialty', replace : 'U03', value :	'Urology'},
		{column : 'Specialty', replace : 'U04', value :	'Urology Oncology'},
		{column : 'Specialty', replace : 'V01', value :	'Vascular and Interventional Radiology'},
		{column : 'Specialty', replace : 'V02', value :	'Vascular Surgery'},
		{column : 'Specialty', replace : 'Z01', value :	'Pathology'},
		{column : 'Specialty', replace : 'Z02', value :	'Hospitalist'},
		{column : 'Specialty', replace : 'Z03', value :	'Perinatology'},
		{column : 'Specialty', replace : 'Z04', value :	'Urgent Care'},
		{column : 'Specialty', replace : 'Z05', value :	'Emergency Medicine'},
		{column : 'Specialty', replace : 'Z06', value :	'Hand Surgery'},
		{column : 'Specialty', replace : 'Z07', value :	'Otology and Neurology'},
		{column : 'Specialty', replace : 'Z08', value :	'Child and Adolescent Medicine'},
		{column : 'Specialty', replace : 'Z09', value :	'Neonatal Perinatal Medicine'},
		{column : 'Specialty', replace : 'Z10', value :	'OB Hospitalist'},
		{column : 'Specialty', replace : 'Z11', value :	'Neonatal Nurse Practitioner'},
		{column : 'FacilityProgramType', replace : '01', value : 'Urgent Care'},
		{column : 'FacilityProgramType', replace : '02', value : 'Durable Medical Equipment'},
		{column : 'FacilityProgramType', replace : '03', value : 'Hospital-LTAC (Long Term Acute Care)'},
		{column : 'FacilityProgramType', replace : '04', value : 'Hospital'},
		{column : 'FacilityProgramType', replace : '05', value : 'Radiology'},
		{column : 'FacilityProgramType', replace : '06', value : 'Sleep Medicine'},
		{column : 'FacilityProgramType', replace : '07', value : 'Skilled Nursing Facility'},
		{column : 'FacilityProgramType', replace : '08', value : 'Home Health'},
		{column : 'FacilityProgramType', replace : '10', value : 'Prosthetic & Orthotic'},
		{column : 'FacilityProgramType', replace : '11', value : 'Ambulatory Surgery Center'},
		{column : 'FacilityProgramType', replace : '12', value : 'Dialysis Center'},
		{column : 'FacilityProgramType', replace : '13', value : 'Cardiac Diagnostic Testing'},
		{column : 'FacilityProgramType', replace : '14', value : 'Home Infusion'},
		{column : 'FacilityProgramType', replace : '15', value : 'Rehab Facility-Outpatient'},
		{column : 'FacilityProgramType', replace : '16', value : 'Diabetes Education'},
		{column : 'FacilityProgramType', replace : '17', value : 'Inpatient Rehab'},
		{column : 'FacilityProgramType', replace : '18', value : 'Oncology'},
		{column : 'FacilityProgramType', replace : '19', value : 'Psychiatry – Rosen/FH Only'},
		{column : 'FacilityProgramType', replace : '20', value : 'Outpatient Surgery'},
		{column : 'FacilityProgramType', replace : '21', value : 'Walk-in Clinic'},
		{column : 'FacilityProgramType', replace : '22', value : 'Hospice'},
		{column : 'FacilityProgramType', replace : '23', value : 'Laboratory'},
		{column : 'FacilityProgramType', replace : '24', value : 'Women\'s Medicine'},
		{column : 'FacilityProgramType', replace : '25', value : 'Gamma Knife'},
		{column : 'FacilityProgramType', replace : '26', value : 'Birthing Center'},
		{column : 'FacilityProgramType', replace : '28', value : 'Lithotripsy'},
		{column : 'FacilityProgramType', replace : '29', value : 'Mental Health Center – Rosen/FH Only'},
		{column : 'FacilityProgramType', replace : '30', value : 'Wound Care'},
		{column : 'FacilityProgramType', replace : '31', value : 'Diagnostic Testing'},
		{column : 'FacilityProgramType', replace : '32', value : 'Emergency Department'},
		{column : 'FacilityProgramType', replace : '33', value : 'Community Health Centers'},
		{column : 'FacilityProgramType', replace : '34', value : 'Audiology'},
		{column : 'FacilityProgramType', replace : '35', value : 'Neonatal Nurse Practitioner'},
		{column : 'FacilityProgramType', replace : '36', value : 'Ambulance'},
		{column : 'FacilityProgramType', replace : '38', value : 'Transplant'},
		{column : 'FacilityProgramType', replace : '39', value : 'Fitness Center'},
		{column : 'FacilityProgramType', replace : '40', value : 'GI Center'},
		{column : 'FacilityProgramType', replace : '41', value : 'Lactation Center'},
		{column : 'FacilityProgramType', replace : '42', value : 'Cardiac Rehabilitation'},
		{column : 'FacilityProgramType', replace : '43', value : 'Interventional Radiology'},
		{column : 'ProviderDegree', replace : 'APRN', value : 'Advanced Practice Registered Nurse'},
		{column : 'ProviderDegree', replace : 'AuD', value : 'Audiology'},
		{column : 'ProviderDegree', replace : 'BA', value : 'Bachelors'},
		{column : 'ProviderDegree', replace : 'BCaBA', value : 'Board Certified Assistant Behavior Analyst'},
		{column : 'ProviderDegree', replace : 'BCBA', value : 'Board Certified Behavior Analyst'},
		{column : 'ProviderDegree', replace : 'BS', value : 'BS'},
		{column : 'ProviderDegree', replace : 'BSN', value : 'BSN'},
		{column : 'ProviderDegree', replace : 'CNM', value : 'CNM'},
		{column : 'ProviderDegree', replace : 'CRNA', value : 'CRNA'},
		{column : 'ProviderDegree', replace : 'CST', value : 'CST'},
		{column : 'ProviderDegree', replace : 'DC', value : 'DC'},
		{column : 'ProviderDegree', replace : 'DDS', value : 'DDS'},
		{column : 'ProviderDegree', replace : 'DMD', value : 'DMD'},
		{column : 'ProviderDegree', replace : 'DMD, MD', value : 'Doctorate of Medical Dentistry, Medical Doctor'},
		{column : 'ProviderDegree', replace : 'DNO', value : 'Doctor Of Nursing Practice'},
		{column : 'ProviderDegree', replace : 'DO', value : 'DO'},
		{column : 'ProviderDegree', replace : 'DO, MPH', value : 'Doctor of Osteopathy, Masters in Public Health'},
		{column : 'ProviderDegree', replace : 'DPM', value : 'DPM'},
		{column : 'ProviderDegree', replace : 'LCSW', value : 'Licensed Clinical Social Worker'},
		{column : 'ProviderDegree', replace : 'LMFT', value : 'License Marriage Family Therapist'},
		{column : 'ProviderDegree', replace : 'LMHC', value : 'Licensed Mental Health Counselor'},
		{column : 'ProviderDegree', replace : 'MA', value : 'Masters'},
		{column : 'ProviderDegree', replace : 'MBBS', value : 'MBBS'},
		{column : 'ProviderDegree', replace : 'MD', value : 'MD'},
		{column : 'ProviderDegree', replace : 'MD, MPH', value : 'Medical Doctor with Masters in Public Health'},
		{column : 'ProviderDegree', replace : 'MD, PhD', value : 'Medical Doctor with PhD'},
		{column : 'ProviderDegree', replace : 'MS', value : 'MS'},
		{column : 'ProviderDegree', replace : 'MSN', value : 'MSN'},
		{column : 'ProviderDegree', replace : 'MSW', value : 'MSW'},
		{column : 'ProviderDegree', replace : 'NP', value : 'NP'},
		{column : 'ProviderDegree', replace : 'OD', value : 'OD'},
		{column : 'ProviderDegree', replace : 'PA', value : 'PA'},
		{column : 'ProviderDegree', replace : 'PA-C', value : 'Physician Assistant Certified'},
		{column : 'ProviderDegree', replace : 'PhD', value : 'Doctorate'},
		{column : 'ProviderDegree', replace : 'PsyD', value : 'PsyD'},
		{column : 'ProviderDegree', replace : 'RD', value : 'Registered Dietician'},
		{column : 'ProviderDegree', replace : 'RN', value : 'Registered Nurse'},
		{column : 'ProviderDegree', replace : 'SW', value : 'Social Worker'},
		{column : 'ProviderTier', replace : 'I', value :	'In-Network - Tier 1'},
		{column : 'ProviderTier', replace : 'II', value :	'Out-Of-Network - Tier 2'},
		{column : 'ProviderTier', replace : 'III', value :	'Sub Network - Tier 3'},
		{column : 'ProviderTier', replace : 'IV', value :	'(User Def) - Tier 4'},
		{column : 'ProviderTier', replace : 'V', value :	'(User Def) - Tier 5'}],
	REPORTS : [
		{
			SOQL : 'SELECT NPI__c, Tax_ID__c, Group__c, First_Name__c, Last_Name__c, Middle_Name__c, Title__c, GroupName__c, Gender__c, Attribution__c, License_Number__c, Malpractice_Exp_Date__c, DEA_Expiration_Date__c, DEA_Number__c, FHHS_Directory__c, Ages_Seen__c, Accepting_New_Patients__c, Provider_Affiliation__c FROM PHSO_Reporting__c WHERE ContactRecordType__c=\'Provider\' AND NPI__c != null AND Tax_ID__c != null AND Group__c != null AND First_Name__c != null AND Last_Name__c != null AND GroupName__c != null AND Gender__c != null AND FHHS_Directory__c != null AND Accepting_New_Patients__c != null AND Provider_Affiliation__c != null ORDER BY NPI__c',
			FILENAME : '_FH_Provider',
			CSV_DELIMITER : '|',
			CHUNK_SIZE : 20000,
			EXTENSION : '.txt',
			REFTYPES : null,
			ADDRESSES : [],
			RULES : [{action : 'update', field : 'attributes', column : 'type'},
				{action : 'replace', field : 'type', operator : 'equals', value : '[\d]+', replace : '11'},
				{action : 'format', field : 'Tax_ID__c', format : 'number'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : 'PG', replace : '01'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '2G', replace : '02'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '3G', replace : '03'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '4G', replace : '04'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '5G', replace : '05'},
				{action : 'format', field : 'Title__c', format : 'nospaces'},
				{action : 'prepend', field : 'Title__c', column : 'suffix'},
				{action : 'replace', field : 'Gender__c', operator : 'equals', value : 'Female', replace : 'F'},
				{action : 'replace', field : 'Gender__c', operator : 'equals', value : 'Male', replace : 'M'},
				{action : 'replace', field : 'Attribution__c', operator : 'equals', value : 'PCP', replace : 'Y'},
				{action : 'replace', field : 'Attribution__c', operator : 'notequals', value : 'Y', replace : 'N'},
				{action : 'format', field : 'Malpractice_Exp_Date__c', format : 'date'},
				{action : 'format', field : 'DEA_Expiration_Date__c', format : 'date'},
				{action : 'replace', field : 'FHHS_Directory__c', operator : 'equals', value : 'No', replace : 'N'},
				{action : 'replace', field : 'FHHS_Directory__c', operator : 'equals', value : 'Yes', replace : 'Y'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '01', value : '6 months and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '02', value : '1 year and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '03', value : '2 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '04', value : '3 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '05', value : '4 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '06', value : '5 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '07', value : '6 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '08', value : '7 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '09', value : '8 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '10', value : '9 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '11', value : '10 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '12', value : '11 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '13', value : '12 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '14', value : '13 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '15', value : '14 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '16', value : '15 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '17', value : '15 years and younger'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '18', value : '16 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '19', value : '16 years and younger'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '20', value : '17 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '21', value : '17 years and younger'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '22', value : '18 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '23', value : '18 years and younger'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '24', value : '19 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '25', value : '19 years and younger'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '26', value : '20 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '27', value : '20 years and younger'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '28', value : '21 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '29', value : '21 years and younger'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '30', value : '60 years and older'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '31', value : 'Neonatal'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '32', value : 'All Ages'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '33', value : 'No Age Range Specified'},
				{action : 'replace', field : 'Ages_Seen__c', operator : 'equals', replace : '33', value : null},
				{action : 'prepend', field : 'Accepting_New_Patients__c', column : 'ProviderEffDate'},
				{action : 'replace', field : 'ProviderEffDate', operator : 'today'},
				{action : 'replace', field : 'Accepting_New_Patients__c', operator : 'equals', value : 'No', replace : 'N'},
				{action : 'replace', field : 'Accepting_New_Patients__c', operator : 'equals', value : 'Yes', replace : 'Y'},
				{action : 'append', column : 'termination_date'}]
			},
		{
			SOQL : 'SELECT NPI__c, Tax_ID__c, Group__c, GroupNPI__c, GroupName__c, OrgProviderGroupc__c, PhysicalAddressStreet1a__c, PhysicalAddressStreet1b__c, PhysicalAddressCity1__c, PhysicalAddressState1__c, PhysicalAddressPostalCode1__c, PhysicalAddressCounty1__c, Phone1__c, Fax1__c, MonDirectory1Format__c, TuesDirectory1Format__c, WedDirectory1Format__c, ThursDirectory1Format__c, FriDirectory1Format__c, SatDirectory1Format__c, SunDirectory1Format__c, PhysicalAddressStreet2a__c, PhysicalAddressStreet2b__c, PhysicalAddressCity2__c, PhysicalAddressState2__c, PhysicalAddressPostalCode2__c, PhysicalAddressCounty2__c, Phone2__c, Fax2__c, MonDirectory2Format__c, TuesDirectory2Format__c, WedDirectory2Format__c, ThursDirectory2Format__c, FriDirectory2Format__c, SatDirectory2Format__c, SunDirectory2Format__c, PhysicalAddressStreet3a__c, PhysicalAddressStreet3b__c, PhysicalAddressCity3__c, PhysicalAddressState3__c, PhysicalAddressPostalCode3__c, PhysicalAddressCounty3__c, Phone3__c, Fax3__c, MonDirectory3Format__c, TuesDirectory3Format__c, WedDirectory3Format__c, PhysicalAddressStreet4a__c, PhysicalAddressStreet4b__c, PhysicalAddressCity4__c, PhysicalAddressState4__c, PhysicalAddressPostalCode4__c, PhysicalAddressCounty4__c, Phone4__c, Fax4__c, MonDirectory4Format__c, TuesDirectory4Format__c, WedDirectory4Format__c, ThursDirectory4Format__c, FriDirectory4Format__c, SatDirectory4Format__c, SunDirectory4Format__c, PhysicalAddressStreet5a__c, PhysicalAddressStreet5b__c, PhysicalAddressCity5__c, PhysicalAddressState5__c, PhysicalAddressPostalCode5__c, PhysicalAddressCounty5__c, Phone5__c, Fax5__c, MonDirectory5Format__c, TuesDirectory5Format__c, WedDirectory5Format__c, ThursDirectory5Format__c, FriDirectory5Format__c, SatDirectory5Format__c, SunDirectory5Format__c, OtherStreet__c, OtherStreet2__c, OtherCity__c, OtherState__c, OtherPostalCode__c, Billing_County__c, Billing_Phone__c, Billing_Fax__c, Website__c FROM PHSO_Reporting__c WHERE ContactRecordType__c=\'Provider\' AND NPI__c != null AND Tax_ID__c != null AND Group__c != null AND First_Name__c != null AND Last_Name__c != null AND GroupName__c != null AND Gender__c != null AND FHHS_Directory__c != null AND Accepting_New_Patients__c != null AND Provider_Affiliation__c != null AND PhysicalAddressStreet1a__c != null AND PhysicalAddressCity1__c != null AND PhysicalAddressState1__c != null AND PhysicalAddressPostalCode1__c != null AND PhysicalAddressCounty1__c != null AND Phone1__c != null AND Fax1__c != null ORDER BY NPI__c',
			FILENAME : '_FH_ProviderAddress',
			CSV_DELIMITER : '|',
			CHUNK_SIZE : 20000,
			EXTENSION : '.txt',
			REFTYPES : null,
			ADDRESSES : [{id : 'NPI__c', address1 : 'PhysicalAddressStreet1a__c', address2 : 'PhysicalAddressStreet1b__c', city : 'PhysicalAddressCity1__c', state : 'PhysicalAddressState1__c', zip : 'PhysicalAddressPostalCode1__c', county : 'PhysicalAddressCounty1__c', phone : 'Phone1__c', fax : 'Fax1__c', monday : 'MonDirectory1Format__c', tuesday : 'TuesDirectory1Format__c', wednesday : 'WedDirectory1Format__c', thursday : 'ThursDirectory1Format__c', friday : 'FriDirectory1Format__c', saturday : 'SatDirectory1Format__c', sunday : 'SunDirectory1Format__c'},
				{id : 'NPI__c', address1 : 'PhysicalAddressStreet2a__c', address2 : 'PhysicalAddressStreet2b__c', city : 'PhysicalAddressCity2__c', state : 'PhysicalAddressState2__c', zip : 'PhysicalAddressPostalCode2__c', county : 'PhysicalAddressCounty2__c', phone : 'Phone2__c', fax : 'Fax2__c', monday : 'MonDirectory2Format__c', tuesday : 'TuesDirectory2Format__c', wednesday : 'WedDirectory2Format__c', thursday : 'ThursDirectory2Format__c', friday : 'FriDirectory2Format__c', saturday : 'SatDirectory2Format__c', sunday : 'SunDirectory2Format__c'},
				{id : 'NPI__c', address1 : 'PhysicalAddressStreet3a__c', address2 : 'PhysicalAddressStreet3b__c', city : 'PhysicalAddressCity3__c', state : 'PhysicalAddressState3__c', zip : 'PhysicalAddressPostalCode3__c', county : 'PhysicalAddressCounty3__c', phone : 'Phone3__c', fax : 'Fax3__c', monday : 'MonDirectory3Format__c', tuesday : 'TuesDirectory3Format__c', wednesday : 'WedDirectory3Format__c', thursday : 'ThursDirectory3Format__c', friday : 'FriDirectory3Format__c', saturday : 'SatDirectory3Format__c', sunday : 'SunDirectory3Format__c'},
				{id : 'NPI__c', address1 : 'PhysicalAddressStreet4a__c', address2 : 'PhysicalAddressStreet4b__c', city : 'PhysicalAddressCity4__c', state : 'PhysicalAddressState4__c', zip : 'PhysicalAddressPostalCode4__c', county : 'PhysicalAddressCounty4__c', phone : 'Phone4__c', fax : 'Fax4__c', monday : 'MonDirectory4Format__c', tuesday : 'TuesDirectory4Format__c', wednesday : 'WedDirectory4Format__c', thursday : 'ThursDirectory4Format__c', friday : 'FriDirectory4Format__c', saturday : 'SatDirectory4Format__c', sunday : 'SunDirectory4Format__c'},
				{id : 'NPI__c', address1 : 'PhysicalAddressStreet5a__c', address2 : 'PhysicalAddressStreet5b__c', city : 'PhysicalAddressCity5__c', state : 'PhysicalAddressState5__c', zip : 'PhysicalAddressPostalCode5__c', county : 'PhysicalAddressCounty5__c', phone : 'Phone5__c', fax : 'Fax5__c', monday : 'MonDirectory5Format__c', tuesday : 'TuesDirectory5Format__c', wednesday : 'WedDirectory5Format__c', thursday : 'ThursDirectory5Format__c', friday : 'FriDirectory5Format__c', saturday : 'SatDirectory5Format__c', sunday : 'SunDirectory5Format__c'},
				{id : 'NPI__c', address1 : 'OtherStreet__c', address2 : 'OtherStreet2__c', city : 'OtherCity__c', state : 'OtherState__c', zip : 'OtherPostalCode__c', county : 'Billing_County__c', phone : 'Billing_Phone__c', fax : 'Billing_Fax__c', monday : '', tuesday : '', wednesday : '', thursday : '', friday : '', saturday : '', sunday : ''}],
			RULES : [{action : 'format', field : 'Tax_ID__c', format : 'number'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : 'PG', replace : '01'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '2G', replace : '02'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '3G', replace : '03'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '4G', replace : '04'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '5G', replace : '05'}]
			},
		{
			SOQL : 'SELECT NPI__c, Tax_ID__c, Group__c, Primary_Language__c, HospitalAffiliationc__c, Hospital_Affiliation_2__c, Hospital_Affiliation_3__c, Hospital_Affiliation_4__c, Hospital_Affiliation_5__c, Hospital_Affiliation_6__c, Hospital_Affiliation_7__c, Hospital_Affiliation_8__c, Hospital_Affiliation_9__c, Hospital_Affiliation_10__c, Practice__r.Name, Tier__c, Primary_Specialty__c, Board_Speciality_P__c, Board_Speciality_S__c, Board_Specialty_Tertiary__c, Board_Certified_P__c, Board_Certifying_Body_P__c, Board_Certified_S__c, Board_Certifying_Body_S__c, Board_Certified_T__c, Board_Certifying_Body_T__c, Commercial__c, Medicare__c, FH_Employees__c, Rosen__c FROM PHSO_Reporting__c WHERE ContactRecordType__c=\'Provider\' AND NPI__c != null AND Tax_ID__c != null AND Group__c != null AND First_Name__c != null AND Last_Name__c != null AND GroupName__c != null AND Gender__c != null AND FHHS_Directory__c != null AND Accepting_New_Patients__c != null AND Provider_Affiliation__c != null ORDER BY NPI__c',
			FILENAME : '_FH_ProviderRef',
			CSV_DELIMITER : '|',
			CHUNK_SIZE : 20000,
			EXTENSION : '.txt',
			REFTYPES : {
				BCP : {val1 : 'Board_Certified_P__c', val2 : 'Board_Certifying_Body_P__c'},
				BCS : {val1 : 'Board_Certified_S__c', val2 : 'Board_Certifying_Body_S__c'},
				BCT : {val1 : 'Board_Certified_T__c', val2 : 'Board_Certifying_Body_T__c'},
				GP : {val1 : 'Practice__r|Name'},
				HA : {val2 : 'HospitalAffiliationc__c|Hospital_Affiliation_2__c|Hospital_Affiliation_3__c|Hospital_Affiliation_4__c|Hospital_Affiliation_5__c|Hospital_Affiliation_6__c|Hospital_Affiliation_7__c|Hospital_Affiliation_8__c|Hospital_Affiliation_9__c|Hospital_Affiliation_10__c'},
				N : {desc : 'Commercial__c|Medicare__c|FH_Employees__c|Rosen__c'},
				L : {val1 : 'Primary_Language__c'},
				SP : {val1 : 'Primary_Specialty__c'},//Board_Speciality_P__c'},
				SS : {val1 : 'Board_Speciality_S__c'},
				ST : {val1 : 'Board_Specialty_Tertiary__c'},
				PT : {val1 : 'Tier__c'}},
			ADDRESSES : [],
			RULES : [{action : 'format', field : 'Tax_ID__c', format : 'number'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : 'PG', replace : '01'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '2G', replace : '02'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '3G', replace : '03'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '4G', replace : '04'},
				{action : 'replace', field : 'Group__c', operator : 'equals', value : '5G', replace : '05'}]
			},
		{
			SOQL : 'SELECT Maximizer_Client_Id_Ancillary__c, GroupName__c, Tax_ID__c, NPI__c, FHHS_Directory__c, HospitalAffiliationc__c FROM PHSO_Reporting__c WHERE AccountRecordType__c=\'Ancillary\' AND Maximizer_Client_Id_Ancillary__c != null AND GroupName__c != null AND Tax_ID__c != null AND NPI__c != null AND FHHS_Directory__c != null ORDER BY Maximizer_Client_Id_Ancillary__c',
			FILENAME : '_FH_Ancillary',
			CSV_DELIMITER : '|',
			CHUNK_SIZE : 20000,
			EXTENSION : '.txt',
			REFTYPES : null,
			ADDRESSES : [],
			RULES : [{action : 'update', field : 'attributes', column : 'type'},
				{action : 'replace', field : 'type', operator : 'equals', value : '[\d]+', replace : '11'},
				{action : 'format', field : 'Tax_ID__c', format : 'number'},
				{action : 'replace', field : 'FHHS_Directory__c', operator : 'equals', value : 'Yes', replace : 'Y'},
				{action : 'replace', field : 'FHHS_Directory__c', operator : 'equals', value : 'No', replace : 'N'},
				{action : 'append', column : 'Star_Rating'}]
			},
		{
			SOQL : 'SELECT Maximizer_Client_Id_Ancillary__c, PhysicalAddressStreet1a__c, PhysicalAddressStreet1b__c, PhysicalAddressCity1__c, PhysicalAddressState1__c, PhysicalAddressPostalCode1__c, PhysicalAddressCounty1__c, Phone1__c, Fax1__c, MonDirectory1Format__c, TuesDirectory1Format__c, WedDirectory1Format__c, ThursDirectory1Format__c, FriDirectory1Format__c, SatDirectory1Format__c, SunDirectory1Format__c, PhysicalAddressStreet2a__c, PhysicalAddressStreet2b__c, PhysicalAddressCity2__c, PhysicalAddressState2__c, PhysicalAddressPostalCode2__c, PhysicalAddressCounty2__c, Phone2__c, Fax2__c, MonDirectory2Format__c, TuesDirectory2Format__c, WedDirectory2Format__c, ThursDirectory2Format__c, FriDirectory2Format__c, SatDirectory2Format__c, SunDirectory2Format__c, PhysicalAddressStreet3a__c, PhysicalAddressStreet3b__c, PhysicalAddressCity3__c, PhysicalAddressState3__c, PhysicalAddressPostalCode3__c, PhysicalAddressCounty3__c, Phone3__c, Fax3__c, MonDirectory3Format__c, TuesDirectory3Format__c, WedDirectory3Format__c, PhysicalAddressStreet4a__c, PhysicalAddressStreet4b__c, PhysicalAddressCity4__c, PhysicalAddressState4__c, PhysicalAddressPostalCode4__c, PhysicalAddressCounty4__c, Phone4__c, Fax4__c, MonDirectory4Format__c, TuesDirectory4Format__c, WedDirectory4Format__c, ThursDirectory4Format__c, FriDirectory4Format__c, SatDirectory4Format__c, SunDirectory4Format__c, PhysicalAddressStreet5a__c, PhysicalAddressStreet5b__c, PhysicalAddressCity5__c, PhysicalAddressState5__c, PhysicalAddressPostalCode5__c, PhysicalAddressCounty5__c, Phone5__c, Fax5__c, MonDirectory5Format__c, TuesDirectory5Format__c, WedDirectory5Format__c, ThursDirectory5Format__c, FriDirectory5Format__c, SatDirectory5Format__c, SunDirectory5Format__c, OtherStreet__c, OtherStreet2__c, OtherCity__c, OtherState__c, OtherPostalCode__c, Billing_County__c, Billing_Phone__c, Website__c FROM PHSO_Reporting__c WHERE AccountRecordType__c=\'Ancillary\' AND Maximizer_Client_Id_Ancillary__c != null AND GroupName__c != null AND Tax_ID__c != null AND NPI__c != null AND FHHS_Directory__c != null AND PhysicalAddressStreet1a__c != null AND PhysicalAddressCity1__c != null AND PhysicalAddressState1__c != null AND PhysicalAddressPostalCode1__c != null AND PhysicalAddressCounty1__c != null AND Phone1__c != null ORDER BY Maximizer_Client_Id_Ancillary__c',
			FILENAME : '_FH_AncillaryAddress',
			CSV_DELIMITER : '|',
			CHUNK_SIZE : 20000,
			EXTENSION : '.txt',
			REFTYPES : null,
			ADDRESSES : [{id : 'Maximizer_Client_Id_Ancillary__c', address1 : 'PhysicalAddressStreet1a__c', address2 : 'PhysicalAddressStreet1b__c', city : 'PhysicalAddressCity1__c', state : 'PhysicalAddressState1__c', zip : 'PhysicalAddressPostalCode1__c', county : 'PhysicalAddressCounty1__c', phone : 'Phone1__c', monday : 'MonDirectory1Format__c', tuesday : 'TuesDirectory1Format__c', wednesday : 'WedDirectory1Format__c', thursday : 'ThursDirectory1Format__c', friday : 'FriDirectory1Format__c', saturday : 'SatDirectory1Format__c', sunday : 'SunDirectory1Format__c'},
				{id : 'Maximizer_Client_Id_Ancillary__c', address1 : 'PhysicalAddressStreet2a__c', address2 : 'PhysicalAddressStreet2b__c', city : 'PhysicalAddressCity2__c', state : 'PhysicalAddressState2__c', zip : 'PhysicalAddressPostalCode2__c', county : 'PhysicalAddressCounty2__c', phone : 'Phone2__c', monday : 'MonDirectory2Format__c', tuesday : 'TuesDirectory2Format__c', wednesday : 'WedDirectory2Format__c', thursday : 'ThursDirectory2Format__c', friday : 'FriDirectory2Format__c', saturday : 'SatDirectory2Format__c', sunday : 'SunDirectory2Format__c'},
				{id : 'Maximizer_Client_Id_Ancillary__c', address1 : 'PhysicalAddressStreet3a__c', address2 : 'PhysicalAddressStreet3b__c', city : 'PhysicalAddressCity3__c', state : 'PhysicalAddressState3__c', zip : 'PhysicalAddressPostalCode3__c', county : 'PhysicalAddressCounty3__c', phone : 'Phone3__c', monday : 'MonDirectory3Format__c', tuesday : 'TuesDirectory3Format__c', wednesday : 'WedDirectory3Format__c', thursday : 'ThursDirectory3Format__c', friday : 'FriDirectory3Format__c', saturday : 'SatDirectory3Format__c', sunday : 'SunDirectory3Format__c'},
				{id : 'Maximizer_Client_Id_Ancillary__c', address1 : 'PhysicalAddressStreet4a__c', address2 : 'PhysicalAddressStreet4b__c', city : 'PhysicalAddressCity4__c', state : 'PhysicalAddressState4__c', zip : 'PhysicalAddressPostalCode4__c', county : 'PhysicalAddressCounty4__c', phone : 'Phone4__c', monday : 'MonDirectory4Format__c', tuesday : 'TuesDirectory4Format__c', wednesday : 'WedDirectory4Format__c', thursday : 'ThursDirectory4Format__c', friday : 'FriDirectory4Format__c', saturday : 'SatDirectory4Format__c', sunday : 'SunDirectory4Format__c'},
				{id : 'Maximizer_Client_Id_Ancillary__c', address1 : 'PhysicalAddressStreet5a__c', address2 : 'PhysicalAddressStreet5b__c', city : 'PhysicalAddressCity5__c', state : 'PhysicalAddressState5__c', zip : 'PhysicalAddressPostalCode5__c', county : 'PhysicalAddressCounty5__c', phone : 'Phone5__c', monday : 'MonDirectory5Format__c', tuesday : 'TuesDirectory5Format__c', wednesday : 'WedDirectory5Format__c', thursday : 'ThursDirectory5Format__c', friday : 'FriDirectory5Format__c', saturday : 'SatDirectory5Format__c', sunday : 'SunDirectory5Format__c'},
				{id : 'Maximizer_Client_Id_Ancillary__c', address1 : 'OtherStreet__c', address2 : 'OtherStreet2__c', city : 'OtherCity__c', state : 'OtherState__c', zip : 'OtherPostalCode__c', county : 'Billing_County__c', phone : 'Billing_Phone__c', fax : '', monday : '', tuesday : '', wednesday : '', thursday : '', friday : '', saturday : '', sunday : ''}],
			RULES : [{action : 'format', field : 'Phone', format : 'number'}]
			},
		{
			SOQL : 'SELECT Maximizer_Client_Id_Ancillary__c, Commercial__c, Medicare__c, FH_Employees__c, Rosen__c, Primary_Specialty__c FROM PHSO_Reporting__c WHERE AccountRecordType__c=\'Ancillary\' AND Maximizer_Client_Id_Ancillary__c != null AND GroupName__c != null AND Tax_ID__c != null AND NPI__c != null AND FHHS_Directory__c != null ORDER BY Maximizer_Client_Id_Ancillary__c',
			FILENAME : '_FH_AncillaryRef',
			CSV_DELIMITER : '|',
			CHUNK_SIZE : 20000,
			EXTENSION : '.txt',
			REFTYPES : {
				N : {desc : 'Commercial__c|Medicare__c|FH_Employees__c|Rosen__c'},
				FP : {val1 : 'Primary_Specialty__c'}
			},
			ADDRESSES : [],
			RULES : []
			}
		]
	}

module.exports = config